config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all

  get 'messages/create'
  get 'rooms/show'
  get 'reviews/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

# STRIPE test
scope '/checkout' do
  post 'create',  to:'checkout#create',  as: 'checkout_create'
  get 'cancel',   to:'checkout#cancel',  as: 'checkout_cancel'
  get 'success',  to:'checkout#success', as: 'checkout_success'
end

root to: 'pages#home'
get "/dashboard", to: 'dashboards#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/search", to: 'searches#search'
  get "/activities", to:'searches#browse'

  resources :coach_activities, only: [:index, :show] do
    resources :bookings, only: [:create, :show] do
      put "/validate", to: "bookings#validate"
      put "/refused", to: "bookings#refused"
    end
    resources :bookings, only: [:destroy, :update]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create, :new]
    resources :payments, only: [:create, :new]
  end
  resources :rooms, only: [:show] do
    resources :messages, only: [:create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="main-stickbot">
  <div class="main-footer">
    <p>All right reserved ©CoachMe</p>
    <ul>
      <li><a href="#"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-github" aria-hidden="true"></i></a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logocoachme.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to activities_path do %>
    <i class ="a fa fa-fw fa-lightbulb"></i>Tendances
    <% end %>
    <a href="mailto:coachela@contact.com?subject=Request&body=Please send me a copy of your new program!">
      <i class ="a fa fa-fw fa-envelope"></i>Contact
    </a>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, height: 40, width: 40, gravity: :face, class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Mon Profil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Tableau de Bord", dashboard_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>