config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all

  get 'messages/create'
  get 'rooms/show'
  get 'reviews/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

# STRIPE test
scope '/checkout' do
  post 'create',  to:'checkout#create',  as: 'checkout_create'
  get 'cancel',   to:'checkout#cancel',  as: 'checkout_cancel'
  get 'success',  to:'checkout#success', as: 'checkout_success'
end

root to: 'pages#home'
get "/dashboard", to: 'dashboards#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/search", to: 'searches#search'
  get "/activities", to:'searches#browse'

  resources :coach_activities, only: [:index, :show] do
    resources :bookings, only: [:create, :show] do
      put "/validate", to: "bookings#validate"
      put "/refused", to: "bookings#refused"
    end
    resources :bookings, only: [:destroy, :update]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create, :new]
    resources :payments, only: [:create, :new]
  end
  resources :rooms, only: [:show] do
    resources :messages, only: [:create]
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @payment = Payment.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.booking = Booking.find(params[:booking_id])
    @payment.user = current_user
    if @payment.save!
      redirect_to coach_activity_path(@payment.booking.coach_activity), notice: 'Votre paeiment a été éffectué. Merci!'
    else
      flash[:alert] = "Oups! Une erreur est survenue."
      render :new
    end
  end

  private

  def payment_params
    params.require(:user_id, :booking_id)
  end

end

app/views/payments/new.html.erb
<script>
 function disableSubmit() {
  document.getElementById("btn-payment").disabled = true;
}

function activateButton(element) {

  if(element.checked) {
    document.getElementById("btn-payment").disabled = false;
  }
  else  {
    document.getElementById("btn-payment").disabled = true;
  }

}
</script>

<div class="container payment-container">
  <div class="payment-top d-flex">
    <div class="payment-pp_coach">
      <%= cl_image_tag @booking.coach.photo.key, height: 150, width: 150, gravity: :face, name: "card-avatar-coach", id: "coach_avatar" %>
    </div>
    <div class="payment-top-title">
      <h2>Récapitulatif commande avec <%= @booking.coach.first_name %></h2>
    </div>
  </div>

  <div class="payment-order">
    <div class="card mb-3 payment-order-top">
      <div class="row no-gutters">
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Résumé :</h5>
            <ul class="order-details">
              <br>
              <li> Date : <%= @booking.date_time %> </li>
              <li> Location :</li>
              <li> Participants : <%= @booking.participant_number %> </li>
              <br>
              <li>Sous-Total : <%= @booking.sum_price %> €</li>
              <li>Déduction : <%= @booking.sum_price %> €</li>
              <br>
              <li>Prix à Payer : <%= @booking.sum_price %> €</li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <%= cl_image_tag "https://res.cloudinary.com/dw22pxuaw/image/upload/v1591348098/Home%20Coach%20Me/wesley-tingey-dlxNvA7pVwU-unsplash_vpam7x.jpg", class:"bd-placeholder-img", width:"100%", height:"100%" %>
          <title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/>
        </div>
      </div>
    </div>
    <div class="order-price-payment">
      <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
      <% end %>
      <%= button_to "PROCEDER AU PAIEMENT", checkout_create_path, method: :post, params: {id: @booking.id}, remote: true, id:"btn-payment" %>
    </div>
  </div>
  <br>
  <br>
  <div class="payment-disclaimer">
    <input type="checkbox" name="terms" id="terms" onchange="activateButton(this)">  J'acceptes les termes & Conditions
    <br>
    <br>
    <p>En cliquant sur sur "J'acceptes" vous reconnaissez être en accord avec les termes et conditions d'utilisation de l'application CoachMe : à savoir que nous ne pourrons être tenu responsable d'aucune façon si cela part en cacahuète. Signé "La fine équipe".</p>
  </div>
</div>