config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all

  get 'messages/create'
  get 'rooms/show'
  get 'reviews/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

# STRIPE test
scope '/checkout' do
  post 'create',  to:'checkout#create',  as: 'checkout_create'
  get 'cancel',   to:'checkout#cancel',  as: 'checkout_cancel'
  get 'success',  to:'checkout#success', as: 'checkout_success'
end

root to: 'pages#home'
get "/dashboard", to: 'dashboards#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/search", to: 'searches#search'
  get "/activities", to:'searches#browse'

  resources :coach_activities, only: [:index, :show] do
    resources :bookings, only: [:create, :show] do
      put "/validate", to: "bookings#validate"
      put "/refused", to: "bookings#refused"
    end
    resources :bookings, only: [:destroy, :update]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create, :new]
    resources :payments, only: [:create, :new]
  end
  resources :rooms, only: [:show] do
    resources :messages, only: [:create]
  end

end

app/models/coach_activity.rb
class CoachActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  has_many   :bookings

  include PgSearch::Model
  pg_search_scope :search_by_activity,
    associated_against: {
      activity: [ :name, :description ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/coach_activities_controller.rb
class CoachActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    @coach_activities = CoachActivity.all
    # @coach_activities.activity.name = Activity.name
    if params[:order] == "price"
      @coach_activities = @coach_activities.order(price: :asc)
    elsif params[:order] == "rating"
      @coach_activities = @coach_activities.order(rating: :desc)
    end

    if params[:query]
      @coach_activities = @coach_activities.search_by_activity(params[:query])
          #test markers
          #@users = User.coach.geocoded
          @markers = @coach_activities.map(&:user).map do |user|
            {
              lat: user.latitude,
              lng: user.longitude,
              infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
              image_url: helpers.asset_url("dumbell.svg"),
              id: user.id
            }
          end
        end
      end

      def new
        @coach_activity = CoachActivity.new
      end

      def show
        @coach_activity = CoachActivity.find(params[:id])
        @booking = Booking.new
        @bookings = Booking.where(coach_activity_id: @coach_activity.id)
        @coach = @coach_activity.user
      end

      def create
        @coach_activity = CoachActivity.new(coach_activity_params)
        @coach_activity.user = current_user
        if @coach_activity.save
          redirect_to coach_activity_path(@coach_activity)
        else
          render :new
        end
      end

      private

      def coach_activity_params
        params.require(:coach_activity).permit(:activity_id, :capacity, :start_date, :end_date, :price)
      end
    end

app/views/coach_activities/_info_window.html.erb
<div class="coach-markers">
  <p> <%= cl_image_tag user.photo.key %> </p>
  <ul>
    <li> <%= user.first_name %> </li>
    <li> <%= user.legal %> </li>
  </ul>
</div>

app/views/coach_activities/_list_coach.html.erb
<% coach_activities.each do |coach_activity| %>
<% @bookings = Booking.where(coach_activity_id: coach_activity.id) %>
<%= link_to coach_activity_path(coach_activity) do %>
<div class="card-product" data-user-id="<%= coach_activity.user.id %>">
  <%= cl_image_tag coach_activity.user.photo.key, id: "activity_avatar", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="card-product-infos">
    <h2><%= coach_activity.user.first_name %></h2>
    <p class="details" style="font-size:20px" > Note: <%= rating_star(@bookings) %> </p>
  </div>
  <div class="card-price">
    <h3><%= coach_activity.price.round %> <span>€/h</span></h3>
  </div>
</div>
<% end %>
<% end %>

app/views/coach_activities/index.html.erb
<% title 'Recherche' %>
<% description 'Search page.' %>
<% keywords 'Search, Recherche, Find' %>
<% nofollow %>
<% noindex %>

<div class="container-wrapper d-flex"> <!-- mt-2 -->
  <div class="list-coaches">
    <div class="home-searchbar">
      <%= form_tag coach_activities_path, class: "barsearch", method: :get do %>
      <%= text_field_tag :query, params[:query], class: "form-control search-input", placeholder:"Coach, spécialité..."%>
      <%= button_tag "Rechercher", class: "btn-yellow" %>
      <% end %>
    </div>

    <div class="filter-search row">
      <%= link_to "Tarifs", coach_activities_path(params:{query: params[:query], order: "price"}), class: "filter-btn", remote: true %>
      <%= link_to "Notes", coach_activities_path(params:{query: params[:query], order: "price"}), class: "filter-btn" %>
    </div>
    <div class="search-count">
      <h3 class="result-count"> <%= @coach_activities.count %> coach trouvés </h3>
    </div>
    <div class="cards-product">
      <%= render"list_coach", coach_activities: @coach_activities %>
    </div>
  </div>
  <div id="map" class="position-sticky vh-65" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/coach_activities/index.js.erb
document.querySelector('.cards-product').innerHTML= " <%= j render 'coach_activities/list_coach', coach_activities: @coach_activities %>"

app/views/coach_activities/new.html.erb
<h2>Mon cours</h2>

<%= simple_form_for [ @coach_activity ] do |f| %>

  <div class="form-inputs-boats">
    <%= f.association :activity %>
    <%= f.input :capacity %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :price, :label => "Prix du cours à l'heure" %>
    <%= f.submit "Créer le cours", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'retour à mon Dashboard', dashboard_path %>

app/views/coach_activities/show.html.erb
<div class="container">

  <div class="card-container">


    <div class="card-activity">
      <div class="activity">
        <div class="activity-name mb-4">
          <h3>En quoi consiste cette activité ?</h3>
        </div>
        <div class="activity-descritpion">
          <p> <%= @coach_activity.activity.description %> </p>
        </div>
      </div>
    </div>

    <div class="card-coach">
      <div class="d-flex">
        <div class="info-coach">
          <div><%= cl_image_tag @coach_activity.user.photo.key, height: 218, width: 218, gravity: :face, name: "card-avatar-coach", id: "coach_avatar" %></div>
        </div>
        <div class="coach-name-rating">
          <div class="coach-name">
            <h2> <%= @coach_activity.user.first_name %> </h2>
          </div>
          <%= rating_star(@bookings) %>
        </div>
      </div>
      <div class="speciality-coach">
          <h3 >Spécialités</h3>
        <div class="row-button-specialities">
        <%= link_to @coach_activity.activity.name, coach_activity_path(@coach_activity), class: "button-specialities" %>
        <% @coach_activity.user.coach_activities.shuffle.first(2).each do |coach_activity| %>
          <%= link_to coach_activity.activity.name, coach_activity_path(coach_activity), class: "button-specialities-secondary" %>
        <% end %>
        </div>
      </div>

    </div>
    <div class="card-booking">
      <div class="card-booking-header">
        <div class="activity-name">
          <h2> <%= @coach_activity.activity.name %> </h2>
        </div>
        <div class="activity-price">
          <h1> <%= @coach_activity.price.round %> </h1> <h3>€/h</h3>
        </div>

      </div>

      <div class="form-booking" id="form-booking">
        <div class="form-wrapper">
          <% if current_user %>
            <%= simple_form_for [@coach_activity, @booking], url: coach_activity_bookings_path(@coach_activity), method: :post, remote: true do |f| %>
            <%= f.input :date_time, as: :string, required: false, input_html: {class: "flatpickr"}, placeholder:"Quel jour, quelle heure ?", label: "Date de début du cours" %>
            <%= f.input :duration, input_html: { min: 0, max: 5 }, placeholder:"Pour combien de temps ?", label: "Nombre d'heures" %>
            <%= f.input :participant_number, input_html: { min: 0, max: 5 }, placeholder:"Seul(e) ou accompagné(e) ?", label: "Nombre de participants"  %>
            <%= f.button :submit, "Transpirez avec #{@coach_activity.user.first_name}", class: "button-form", data: {toggle: "modal", target: "#staticBackdrop"} %>
            <% end %>
          <% else %>
          <div class="identify">
            <%= link_to "Identifiez-vous", new_user_session_path, class: "button-form link" %>
          </div>
          <% end %>
        </div>
      </div>

    </div>


  </div>
  <div class="review-map-container">
    <div class="review-count">
      <div class="row-review-count">
        <% coach_activity_reviews = booking_reviews(@bookings) %>
        <% if coach_activity_reviews.is_a? String %>
          <h3> <%= coach_activity_reviews %>  </h3>
        <% else %>
          <h2> <%= coach_activity_reviews.count %>  </h2>
          <h3> commentaires </h3>
        <% end %>
      </div>
        <% if coach_activity_reviews.is_a? String %>
        <h3> Soyez le premier à commenter </h3>
        <% else %>
        <% coach_activity_reviews.each do |review| %>
          <div class="reviews">
            <div class="review-header">
              <p> <%= review.booking.user.first_name %> </p>
              <div class="coach-rating">
                <% review.rating.to_i.times do  %>
                  <%= image_tag "dumbell.svg" %>
                <% end %>
                <% less = 5 - review.rating.to_i  %>
                <% less.times do  %>
                  <%= image_tag "dumbell_white.svg" %>
                <% end %>
              </div>
            </div>
            <div class="review-content">
              <p> <%= review.content %> </p>
            </div>
              <% end %>
              <% end %>
          </div>

    </div>

    <div class="map">

    </div>
  </div>


</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>