config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all

  get 'messages/create'
  get 'rooms/show'
  get 'reviews/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

# STRIPE test
scope '/checkout' do
  post 'create',  to:'checkout#create',  as: 'checkout_create'
  get 'cancel',   to:'checkout#cancel',  as: 'checkout_cancel'
  get 'success',  to:'checkout#success', as: 'checkout_success'
end

root to: 'pages#home'
get "/dashboard", to: 'dashboards#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/search", to: 'searches#search'
  get "/activities", to:'searches#browse'

  resources :coach_activities, only: [:index, :show] do
    resources :bookings, only: [:create, :show] do
      put "/validate", to: "bookings#validate"
      put "/refused", to: "bookings#refused"
    end
    resources :bookings, only: [:destroy, :update]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create, :new]
    resources :payments, only: [:create, :new]
  end
  resources :rooms, only: [:show] do
    resources :messages, only: [:create]
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # after_action :verify_authorized

  def dashboard
    @coach_activities = current_user.coach_activities
    @bookings = current_user.bookings


    if current_user.coach?
      if current_user.location.nil? || current_user.legal.nil? || current_user.licence.nil?
        redirect_to edit_user_registration_path(current_user)
      end
    end

  end
end

app/views/dashboards/dashboard.html.erb
<% title 'Tableau de bord' %>
<% description 'Member dashboard page.' %>
<% keywords 'Dashboard, Tableau de bord, Gestionnaire' %>
<% nofollow %>
<% noindex %>

<div class="dashboard">

<!--   <a class="dash-link active top" id="v-pills-home-tab" data-toggle="pill" role="tab" aria-controls="v-pills-home" aria-selected="true">Mes Activités</a>
  <a class="dash-link middle" id="v-my-bookings-tab" data-toggle="pill" href="#v-my-bookings" role="tab" aria-controls="v-my-bookings" aria-selected="false">Discuter avec mes coachs</a>
  <a class="dash-link bottom" id="v-my-deals-tab" data-toggle="pill" href="#v-my-deals" role="tab" aria-controls="v-my-deals" aria-selected="false">Votre Compte</a> -->

<div class="dash flex-column dash-pills col-md-2" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <%= link_to dashboard_path, class: "dash-link active top" do %>Mes Activités
  <% end %>
  <%= link_to dashboard_path, class: "dash-link middle" do %>Discuter avec mes coachs
  <% end %>
  <%= link_to dashboard_path, class: "dash-link bottom" do %>Votre Compte
  <% end %>
</div>

  <!-- Coach View -->
  <div class="container coach-view-container">
    <div class="row">
      <% if current_user.coach? %>
      <ul>
        <% current_user.coach_activities.map(&:bookings).flatten.each do |booking| %>
        <div>
          <p> <%= "#{booking.coach_activity.activity.name} le #{booking.coach_activity.start_date} au #{booking.coach_activity.end_date}. Prix : #{booking.coach_activity.price} €" %> </p>
          <div class="booking-container-<%= booking.id %>">
            <%= render "bookings/infos", coach_activity: booking.coach_activity, booking: booking %>
          </div>·
          <br>
          <%= link_to "Chat", room_path(booking.room), class:"btn-orange" %>
          <br>
          <br>
        </div>
        <% end %>
      </ul>
      <% end %>
    </div>

    <!-- User View -->
    <div class= "container">
      <div class="dashboard-header">
        <div class="dashboard-header-hello">
          <h2> Bonjour <%= current_user.first_name %> ! </h2>
        </div>
        <div class="dashboard-header-infos">
          <h3> Il y a <%= @bookings.count %> activités en cours </h3>
        </div>
        <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>

    <% if current_user.coach? == false %>
    <% @bookings.each do |booking| %>

    <div class="modal-content">
      <div class="modal-body">
        <div class="content">

          <div class="coach_avatar">
            <div class="avatar-img">
              <%= cl_image_tag booking.coach.photo.key, height: 200, width: 200, gravity: :face, id: "coach_avatar", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            </div>
            <div class="coach-infos">
              <div class="coach-name">
                <h2> <%= booking.coach.first_name %> </h2>
              </div>
              <div class="coach-rating">
                <%= rating_star(booking.coach_activity.bookings) %>
              </div>
              <div class="activity-price">
                <h2> <%= booking.coach_activity.activity.name %> </h2>
                <h2 class="price"> <strong><%= booking.sum_price %></strong> €</h2>
              </div>
              <div class="status">
                <h3> Statut: </h3> <h3 class="orange"> <%= booking.status %> </h3>
              </div>
            </div>
            <%= link_to image_tag("delete.svg"), coach_activity_booking_path(booking.coach_activity, booking), method: :delete, class: "button-delete" %>
          </div>
          <div class="booking-infos">
            <div class="start-date">
              <h3 class="white">Début du cours:</h3>
              <h3> <%= booking.date_time.strftime("%d/%m/%Y-%H:%M") %> </h3>
            </div>
            <div class="end-date">
              <h3 class="white">Durée:</h3>
              <h3> <%= booking.duration %> h </h3>
              <h3 class="white"> Pour </h3>
              <h3> <%= booking.participant_number %> personne(s) </h3>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <% if booking.room != nil %>
        <%= link_to "Envoyer un message", room_path(booking.room), class: "button-specialities2" %>
        <%= link_to "Paiement securisé", new_booking_payment_path(booking), class: "btn btn-payment" %>
        <% end %>
        <% if booking.status == "confirmé" %>
        <%= link_to "Donnez votre avis", new_booking_review_path(booking), class: "button-specialities" %>
        <% end %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/dashboards/old_dashboard.html.erb
    <% if current_user.coach? %>
    <div class="row">
      <% @coach_activities.each do |coach_activity| %>
      <div>
        <p> <%= "#{coach_activity.activity.name} du #{coach_activity.start_date} au #{coach_activity.end_date}. Prix : #{coach_activity.price} €" %> </p>
        <%= link_to "voir ce cours", coach_activity_path(coach_activity) %>
      </div>
      <% coach_activity.bookings.each do |booking| %>
      <div class="booking-container-<%= booking.id %>">
        <%= render "bookings/infos", coach_activity: coach_activity, booking: booking %>
        <%= link_to "Envoyer un message", room_path(booking.room), class: "btn btn-primary" %>
      </div>
      <% end %>
      <% end %>
    </div>
    <div>
      <%= link_to "créez votre cours", new_coach_activity_path  %>
    </div>
    <% end %>

  <!-- User View -->
  <div class= "container">
    <div class="dashboard-header">
      <div class="dashboard-header-hello">
        <h2> Bonjour <%= current_user.first_name %> ! </h2>
      </div>
      <div class="dashboard-header-infos">
        <h3> Il y a <%= @bookings.count %> activités en cours </h3>
      </div>

    </div>
  <% if current_user.coach? == false %>
    <% @bookings.each do |booking| %>

    <div class="modal-content">
      <div class="modal-body">
        <div class="content">
          <div class="coach_avatar">
            <div class="avatar-img">
              <%= cl_image_tag booking.coach.photo.key, height: 200, width: 200, gravity: :face, id: "coach_avatar", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            </div>
            <div class="coach-infos">
              <div class="coach-name">
                <h2> <%= booking.coach.first_name %> </h2>
              </div>
              <div class="coach-rating">
                <%= rating_star(booking.coach_activity.bookings) %>
              </div>
              <div class="activity-price">
                <h2> <%= booking.coach_activity.activity.name %> </h2>
                <h2> <strong><%= booking.sum_price %></strong> €/h </h2>
              </div>
            </div>
          </div>
          <div class="booking-infos">
            <div class="start-date">
              <h3>Début du cours:</h3>
              <h3> <%= booking.start_time.strftime("%d/%m/%Y-%H:%M") %> </h3>
            </div>
            <div class="end-date">
              <h3>Fin du cours:</h3>
              <h3> <%= booking.start_time.strftime("%d/%m/%Y-%H:%M") %> </h3>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Annuler le cours", coach_activity_booking_path(booking.coach_activity, booking), method: :delete, class: "button-specialities" %>
        <% if booking.room != nil %>
          <%= link_to "Envoyer un message", room_path(booking.room), class: "button-specialities" %>
        <% end %>
        <%= link_to "Donnez votre avis", new_booking_review_path(booking), class: "button-specialities" %>
      </div>
    </div>
    <% end %>
  <% end %>
  </div>
</div>